"""Heroes.external_id

Revision ID: 94c33060cb85
Revises: e5e10986fe96
Create Date: 2025-07-14 20:53:02.960617

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94c33060cb85"
down_revision: Union[str, Sequence[str], None] = "e5e10986fe96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("heroes", sa.Column("external_id", sa.Integer(), nullable=True))
    op.drop_constraint(op.f("uq_heroes_name"), "heroes", type_="unique")
    op.create_unique_constraint(op.f("uq_heroes_external_id"), "heroes", ["external_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_heroes_external_id"), "heroes", type_="unique")
    op.create_unique_constraint(op.f("uq_heroes_name"), "heroes", ["name"], postgresql_nulls_not_distinct=False)
    op.drop_column("heroes", "external_id")
    # ### end Alembic commands ###
